architecture: Xception
#pooling: avg
augmentation:
 Fliplr: 0.5
 Flipud: 0.5
classes: 28
activation: sigmoid
weights: imagenet
shape: [512, 512, 4]
optimizer: Adam
batch: 8
lr: 0.0001
copyWeights: true
metrics:
  - binary_accuracy
  - macro_f1
primary_metric: val_macro_f1
primary_metric_mode: max
callbacks:
  EarlyStopping:
    patience: 15
    monitor: val_macro_f1
    mode: max
    verbose: 1

loss: f1_loss
stages:
  - epochs: 3
  - epochs: 40
    loss: f1_loss
    extra_callbacks:
      CyclicLR:
        base_lr: 0.000001
        max_lr: 0.001
        mode: triangular2
        step_size: 12000