architecture: DenseNet201
pooling: avg
augmentation:
 Fliplr: 0.5
 Flipud: 0.5
classes: 28
activation: sigmoid
weights: imagenet
extra_train_data: train2
shape: [256, 256, 4]
optimizer: Adam
batch: 32
lr: 0.0001
copyWeights: true
metrics:
  - binary_accuracy
  - macro_f1
primary_metric: val_macro_f1
primary_metric_mode: max

callbacks:
  EarlyStopping:
    patience: 15
    monitor: val_macro_f1
    mode: max
    verbose: 1
  CyclicLR:
    base_lr: 0.00001
    max_lr: 0.005
    mode: triangular
    step_size: 3000
loss: binary_crossentropy
stages:
  - epochs: 50
  - epochs: 50
    callbacks:
      CyclicLR:
        base_lr: 0.00001
        max_lr: 0.002
        mode: triangular2
        step_size: 6216
  - epochs: 50
    callbacks:
      CyclicLR:
        base_lr: 0.00001
        max_lr: 0.0002
        mode: triangular2
        step_size: 6216