architecture: Xception
#pooling: avg
augmentation:
 Fliplr: 0.5
 Flipud: 0.5
classes: 28
activation: sigmoid
weights: imagenet
shape: [256, 256, 4]
optimizer: Adam
batch: 40
lr: 0.001
copyWeights: true
metrics:
  - binary_accuracy
  - macro_f1
primary_metric: val_macro_f1
primary_metric_mode: max
callbacks:
  EarlyStopping:
    patience: 15
    monitor: val_macro_f1
    mode: max
    verbose: 1
  CyclicLR:
    base_lr: 0.00001
    max_lr: 0.0001
    mode: triangular2
    step_size: 10000
loss: binary_crossentropy
stages:
  - epochs: 100

